api:
   build: ./dockerfiles
   dockerfile: node
   command: nodemon -L --watch server --watch client/* server/index.js
   links:
      - db
   ports:
      - "8001:8001"
   environment:
      - VIRTUAL_HOST=6element-alpha.ants.builders
      - VIRTUAL_PORT=8001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - NODE_ENV=development
   volumes:
      - ./:/6element
      - ./backups:/backups/
   tty: true
   dns:
      - 8.8.8.8

db:
   build: ./dockerfiles
   dockerfile: postgis
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   tty: true
