citizen:
   build: .
   command: node core/server/citizen.js
   links:
      - db
   ports:
      - 4002:4002
   environment:
      - VIRTUAL_HOST=6citizen.ants.builders 
      - VIRTUAL_PORT=4002
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./core:/6element/core
      - /data/6element:/6element/data
      
      
dashboard:
   build: .
   command: node core/server/dashboard.js
   links:
      - db
      - endpoint
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders 
      - VIRTUAL_PORT=4000
      - INTERNAL_PORT=55555
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./core:/6element/core
      - /data/6element:/6element/data
   restart: always
   
   
endpoint:
   build: .
   command: node core/server/endpoint.js
   links:
      - db
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - INTERNAL_PORT=55555
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./core:/6element/core
   restart: always


admin:
   build: .
   command: node core/server/admin.js
   links:
      - db
      - endpoint
   ports:
      - "4001:4001"
   environment:
      - VIRTUAL_HOST=sensors.ants.builders 
      - VIRTUAL_PORT=4001
      - INTERNAL_PORT=55555
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=production
   volumes:
      - ./core:/6element/core
      - /data/6element:/6element/app/data
   restart: always
   
   
db:
   image: postgres:9.4
   environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   restart: always