api:
   build: ./dockerfiles
   dockerfile: node
   command: node server/index.js
   links:
      - db
   ports:
      - "3500:3500"
   environment:
      - VIRTUAL_HOST=6element.fr,6element.org,6element.net,6element.eu
      - VIRTUAL_PORT=3500
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - NODE_ENV=production
   volumes:
      - ./:/6element
      - /data/6element/backups:/backups/
   tty: true

db:
   build: ./dockerfiles
   dockerfile: postgis
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   tty: true
