api:
   build: ./dockerfiles
   dockerfile: node
   command: node server/index.js
   links:
      - db
   ports:
      - "8000:8000"
   environment:
      - VIRTUAL_HOST=6element.fr
      - VIRTUAL_PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - NODE_ENV=production
   volumes:
      - ./:/6element
      - ./backups:/backups/
   tty: true

db:
   build: ./dockerfiles
   dockerfile: postgis
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   tty: true
