api:
   build: ./dockerfiles
   dockerfile: node
   command: nodemon --watch server --watch src/index.html server/index.js
   links:
      - db
   ports:
      - "35000:35000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders
      - VIRTUAL_PORT=35000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - NODE_ENV=development
   volumes:
      - ./:/6element
      - ./backups:/backups/
   tty: true

db:
   build: ./dockerfiles
   dockerfile: postgis
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   tty: true
